# Generated by Django 3.2.5 on 2021-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210909_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='upachangerequest',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
