# Generated by Django 3.2.5 on 2021-10-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_incomesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomesetting',
            old_name='left_side',
            new_name='bpl_upa_amnt',
        ),
        migrations.RenameField(
            model_name='incomesetting',
            old_name='middle_side',
            new_name='handicap_upa_amnt',
        ),
        migrations.RenameField(
            model_name='incomesetting',
            old_name='right_side',
            new_name='normal_upa_amnt',
        ),
    ]
