# Generated by Django 3.2.5 on 2021-10-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211004_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesetting',
            name='not_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
