# Generated by Django 3.2.5 on 2021-10-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_incomesetting_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesetting',
            name='bpl_upa_amnt',
        ),
        migrations.RemoveField(
            model_name='incomesetting',
            name='handicap_upa_amnt',
        ),
        migrations.RemoveField(
            model_name='incomesetting',
            name='normal_upa_amnt',
        ),
        migrations.RemoveField(
            model_name='incomesetting',
            name='not_available',
        ),
        migrations.AddField(
            model_name='incomesetting',
            name='child_one',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap'), ('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='incomesetting',
            name='child_three',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap'), ('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='incomesetting',
            name='child_two',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap'), ('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True),
        ),
    ]
