# Generated by Django 3.2.5 on 2021-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211004_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesetting',
            name='income',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
