# Generated by Django 3.2.5 on 2021-10-12 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_incomesetting_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_firm', models.BooleanField(default=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=12, null=True)),
                ('firm_name', models.CharField(blank=True, help_text='Enter The Firm Name', max_length=200, null=True)),
                ('firm_image', models.ImageField(blank=True, null=True, upload_to='firm/image/')),
                ('address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('address_three', models.CharField(blank=True, max_length=100, null=True)),
                ('address_four', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('firm_mode', models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Dealer', 'Dealer'), ('Supplier', 'Supplier'), ('Agency', 'Agency'), ('Shopkeeper', 'Shopkeeper'), ('Exporter', 'Exporter'), ('Exporter', 'Exporter'), ('Contractor', 'Contractor'), ('Farmer', 'Farmer')], max_length=12, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
