# Generated by Django 3.2.5 on 2021-10-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_auto_20211026_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_product_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('product_name', models.ImageField(blank=True, null=True, upload_to='tender_product/image/')),
                ('product_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('tender_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_range', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('tender_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=10, null=True)),
                ('tender_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tenderproduct')),
            ],
        ),
    ]
