# Generated by Django 3.2.5 on 2021-10-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tenderproduct_tenderraise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderproduct',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='tenderproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='tender_product/image/'),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
