# Generated by Django 3.2.5 on 2022-01-22 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_auto_20211029_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSettingForWomenOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_one', models.CharField(blank=True, choices=[('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True)),
                ('child_two', models.CharField(blank=True, choices=[('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True)),
                ('child_three', models.CharField(blank=True, choices=[('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True)),
                ('income', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_setting_for_old_women', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_setting_for_old_women_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income Setting For Women And Old',
                'verbose_name_plural': 'Income Setting For Women And Old',
            },
        ),
    ]
