# Generated by Django 3.2.5 on 2022-01-22 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_incomesettingforwomenold'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrderToTenderFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('Order Pending', 'Order Pending'), ('Order On The Way', 'Order On The Way'), ('Order Recieved', 'Order Recieved')], default='Order Pending', max_length=17, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tenderraise')),
            ],
        ),
    ]
