# Generated by Django 3.2.5 on 2022-02-05 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_auto_20220130_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePurchaseBreakupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('order_month', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('bulk_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.bulkordertotenderfirm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
