# Generated by Django 3.2.5 on 2022-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_prepurchasebreakuporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproduct',
            name='tender_product_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
