# Generated by Django 3.2.5 on 2022-02-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_finalproductfromtender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproductfromtender',
            old_name='tender_product',
            new_name='final_tender_product',
        ),
    ]
