# Generated by Django 3.2.5 on 2022-02-16 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_rename_tender_product_finalproductfromtender_final_tender_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproductfromtender',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
