# Generated by Django 3.2.5 on 2022-02-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_finalproductfromtender_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproductfromtender',
            name='product_status',
            field=models.CharField(blank=True, choices=[('Non Negotiated', 'Non Negotiated'), ('Negotiated', 'Negotiated')], default='Non Negotiated', max_length=14, null=True),
        ),
    ]
