# Generated by Django 3.2.5 on 2022-02-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_finalproductfromtender_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalproductfromtender',
            name='product_status',
        ),
        migrations.AddField(
            model_name='finalproductfromtender',
            name='negotiated_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
