# Generated by Django 3.2.5 on 2022-02-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20220216_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepurchasebreakuporder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Unsend To Vendor', 'Unsend To Vendor'), ('Send To Vendor', 'Send To Vendor')], default='Unsend To Vendor', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bulkordertotenderfirm',
            name='tender_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.finalproductfromtender'),
        ),
    ]
