# Generated by Django 3.2.5 on 2022-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20220216_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepurchasebreakuporder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Unsend To Vendor', 'Unsend To Vendor'), ('Sent To Vendor', 'Sent To Vendor')], default='Unsend To Vendor', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
