# Generated by Django 3.2.5 on 2022-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20220221_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderraise',
            name='negotiation_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderraise',
            name='tender_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Negotiated', 'Negotiated')], default='Pending', max_length=10, null=True),
        ),
    ]
