# Generated by Django 3.2.5 on 2022-02-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20220221_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepurchasebreakuporder',
            old_name='product_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='prepurchasebreakuporder',
            name='bulk_order',
        ),
        migrations.AddField(
            model_name='prepurchasebreakuporder',
            name='tender_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tenderraise'),
        ),
        migrations.AlterField(
            model_name='bulkordertotenderfirm',
            name='tender_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tenderraise'),
        ),
    ]
