# Generated by Django 3.2.5 on 2022-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20220222_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderraise',
            name='negotiate_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tenderraise',
            name='negotiate_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
