# Generated by Django 3.2.5 on 2022-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20220226_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderraise',
            name='total_product_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
