# Generated by Django 3.2.5 on 2022-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_tenderraise_total_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproduct',
            name='total_product_quantity_by_vendor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
