# Generated by Django 3.2.5 on 2022-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_tenderproduct_total_product_quantity_by_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproduct',
            name='total_product_quantity_by_vendor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
