# Generated by Django 3.2.5 on 2022-02-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_tenderproduct_total_product_quantity_by_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_by_firm', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.PositiveIntegerField(blank=True, null=True)),
                ('tender_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Negotiated', 'Negotiated')], default='Pending', max_length=10, null=True)),
                ('recieved_date', models.DateTimeField(auto_now=True, null=True)),
                ('tender_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tenderraise')),
            ],
        ),
    ]
