# Generated by Django 3.2.5 on 2022-03-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_recievedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedproducts',
            name='tender_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Exchange', 'Exchange')], default='Pending', max_length=10, null=True),
        ),
    ]
