# Generated by Django 3.2.5 on 2022-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_recievedproducts_tender_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedproducts',
            name='tender_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('On Exchange', 'On Exchange'), ('Exchanged', 'Exchanged')], default='Pending', max_length=13, null=True),
        ),
    ]
