# Generated by Django 3.2.5 on 2022-03-06 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0036_storekeepingunit_storelocationdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='storekeepingunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_Store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storekeepingunit',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storekeepingunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_store', to=settings.AUTH_USER_MODEL),
        ),
    ]
