# Generated by Django 3.2.5 on 2022-03-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0038_storekeepingunit_store_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('box_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_quantity_in_box', models.IntegerField(blank=True, default=1, null=True)),
                ('rack_row', models.IntegerField(blank=True, null=True)),
                ('section_number_on_rack', models.IntegerField(blank=True, null=True)),
                ('rack_and_store_design', models.ImageField(blank=True, null=True, upload_to='store/drawing/')),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.storekeepingunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
