# Generated by Django 3.2.5 on 2022-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_productinstore_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievedproducts',
            name='exchange_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
