# Generated by Django 3.2.5 on 2022-03-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_recievedproducts_exchange_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstore',
            name='product_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.recievedproducts'),
        ),
    ]
