# Generated by Django 3.2.5 on 2022-09-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_productinstore_product_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesettingforwomenold',
            name='child_one',
        ),
        migrations.RemoveField(
            model_name='incomesettingforwomenold',
            name='child_three',
        ),
        migrations.RemoveField(
            model_name='incomesettingforwomenold',
            name='child_two',
        ),
        migrations.AddField(
            model_name='incomesettingforwomenold',
            name='category_type',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('BPL', 'BPL'), ('Handicap', 'Handicap'), ('Child Below 18', 'Child Below 18'), ('Senior Citizen', 'Senior Citizen'), ('Mature Female', 'Mature Female')], max_length=15, null=True),
        ),
    ]
