# Generated by Django 3.2.5 on 2023-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20230112_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesetting',
            name='previous_income',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
