# Generated by Django 3.2.5 on 2023-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_incomesetting_previous_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesettingforwomenold',
            name='previous_income_for_women_old',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
