# Generated by Django 3.2.5 on 2023-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_incomesettingforwomenold_previous_income_for_women_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='upachangerequest',
            name='form_name',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Read', 'Read')], default='', max_length=25, null=True),
        ),
    ]
