# Generated by Django 3.2.5 on 2023-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_upachangerequest_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upachangerequest',
            name='form_name',
            field=models.CharField(blank=True, choices=[('Address Form', 'Address Form'), ('Additional Detail Form', 'Additional Detail Form'), ('Beneficiary Detail Form', 'Beneficiary Detail Form'), ('Service Required Form', 'Service Required Form'), ('Operation Mode Form', 'Operation Mode Form')], default='', max_length=25, null=True),
        ),
    ]
