# Generated by Django 3.2.5 on 2021-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UID No.'),
        ),
    ]
