# Generated by Django 3.2.5 on 2021-08-31 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_uid_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_upa',
            field=models.ManyToManyField(blank=True, related_name='linked_upa', to=settings.AUTH_USER_MODEL),
        ),
    ]
