# Generated by Django 3.2.5 on 2021-07-29 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_uid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sponsor UID')),
                ('sponsor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sponsor Name')),
                ('branch', models.CharField(blank=True, choices=[('Test', 'Test'), ('Test_one', 'Test_one')], max_length=50, null=True, verbose_name='Branch Type')),
                ('upa_type', models.CharField(blank=True, choices=[('Test', 'Test'), ('Test_one', 'Test_one')], max_length=50, null=True, verbose_name='UPA Type')),
                ('relation_upa', models.CharField(blank=True, choices=[('Test', 'Test'), ('Test_one', 'Test_one')], max_length=50, null=True, verbose_name='Relation with UPA')),
                ('post_applied', models.CharField(blank=True, max_length=50, null=True, verbose_name='Post Applied For')),
                ('applicant_upa_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Applicant UPA Type')),
                ('applicant_appl_seq_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant Application Sequence Number')),
                ('applicant_coll_ref_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant Collection Refrence Number')),
                ('applicant_reg_seq_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant Registration Sequence Number')),
                ('applicant_dis_id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant Distributor ID(D.I.D) Number')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Applicant Full Name')),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Form Submission Date / Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
