# Generated by Django 3.2.5 on 2021-07-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0008_alter_basicdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name")),
                ('first_name_hg', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name_hg', models.CharField(blank=True, max_length=100, null=True)),
                ('gaurdian_name_hg', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_median_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name_m', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name_m', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_m', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('update_age_dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='accounts.profile')),
            ],
        ),
    ]
