# Generated by Django 3.2.5 on 2021-07-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0009_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPAAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_three', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_four', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('active_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('std_code', models.PositiveIntegerField(blank=True, null=True)),
                ('isd_code', models.PositiveIntegerField(blank=True, null=True)),
                ('p_address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_three', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_four', models.CharField(blank=True, max_length=100, null=True)),
                ('p_landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('p_town', models.CharField(blank=True, max_length=100, null=True)),
                ('p_dictrict', models.CharField(blank=True, max_length=100, null=True)),
                ('p_sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('p_postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('p_country', models.CharField(blank=True, max_length=100, null=True)),
                ('p_state', models.CharField(blank=True, max_length=100, null=True)),
                ('p_telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('p_mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('p_active_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('p_std_code', models.PositiveIntegerField(blank=True, null=True)),
                ('p_isd_code', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_title', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM')], max_length=10, null=True)),
                ('rel_other', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('Gen', 'Gen'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=10, null=True)),
                ('educational_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('self_employeed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=100, null=True)),
                ('assets', models.CharField(blank=True, help_text='Approximate Value', max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('it_pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bussiness_nature', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to='accounts.profile')),
            ],
        ),
    ]
