# Generated by Django 3.2.5 on 2021-08-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0010_additionaldetails_upaaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPAIdentityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upa_type', models.CharField(blank=True, choices=[('Test', 'Test'), ('Test1', 'Test1')], max_length=20, null=True)),
                ('bpl_ration_card_no', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_income_type', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True)),
                ('personal_income', models.CharField(blank=True, max_length=100, null=True)),
                ('cmo_certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_card_id', models.BooleanField(default=False)),
                ('voter_card_id', models.BooleanField(default=False)),
                ('pan_card_id', models.BooleanField(default=False)),
                ('passport_id', models.BooleanField(default=False)),
                ('driving_license_id', models.BooleanField(default=False)),
                ('ration_card_add', models.BooleanField(default=False)),
                ('voter_card_add', models.BooleanField(default=False)),
                ('aadhar_card_add', models.BooleanField(default=False)),
                ('passport_add', models.BooleanField(default=False)),
                ('driving_add', models.BooleanField(default=False)),
                ('id_proof_no', models.CharField(blank=True, max_length=100, null=True)),
                ('id_issued_at', models.DateField(blank=True, null=True)),
                ('id_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('add_proof_no', models.CharField(blank=True, max_length=100, null=True)),
                ('add_issued_at', models.DateField(blank=True, null=True)),
                ('add_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upa_identity', to='accounts.profile')),
            ],
        ),
    ]
