# Generated by Django 3.2.5 on 2021-08-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0011_upaidentityproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_upa', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Daughter', 'Daughter'), ('Son', 'Son')], max_length=20, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('ben_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ben_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ben_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_g_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_g_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_g_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_m_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_m_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('m_m_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('update_age_dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_one', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_three', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_four', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar_card_id', models.BooleanField(default=False)),
                ('voter_card_id', models.BooleanField(default=False)),
                ('pan_card_id', models.BooleanField(default=False)),
                ('passport_id', models.BooleanField(default=False)),
                ('driving_license_id', models.BooleanField(default=False)),
                ('ration_card_add', models.BooleanField(default=False)),
                ('voter_card_add', models.BooleanField(default=False)),
                ('aadhar_card_add', models.BooleanField(default=False)),
                ('passport_add', models.BooleanField(default=False)),
                ('driving_license_add', models.BooleanField(default=False)),
                ('id_proof_no', models.CharField(blank=True, max_length=100, null=True)),
                ('id_issued_at', models.DateField(blank=True, null=True)),
                ('id_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('add_proof_no', models.CharField(blank=True, max_length=100, null=True)),
                ('add_issued_at', models.DateField(blank=True, null=True)),
                ('add_issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_details', to='accounts.profile')),
            ],
        ),
    ]
