# Generated by Django 3.2.5 on 2021-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0012_beneficiarydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upaidentityproof',
            name='upa_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Handicap', 'Handicap'), ('BPL', 'BPL')], max_length=20, null=True),
        ),
    ]
