# Generated by Django 3.2.5 on 2021-08-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0013_alter_upaidentityproof_upa_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessCardFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_bussiness_card', models.PositiveIntegerField(blank=True, null=True)),
                ('pvc_bussiness_card', models.PositiveIntegerField(blank=True, null=True)),
                ('pvc_chip_bussiness_card', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
