# Generated by Django 3.2.5 on 2021-08-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0014_bussinesscardfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorIntroductionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter Sponsor Name', max_length=200, null=True)),
                ('did_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.PositiveIntegerField(blank=True, null=True)),
                ('time_in_bussiness', models.CharField(blank=True, choices=[('3 Month', '3 Month'), ('6 Month', '6 Month'), ('1 Year', '3 Year'), ('More Than 1 Year', 'More Than 1 Year')], max_length=100, null=True)),
                ('time_with_applicant', models.CharField(blank=True, choices=[('3 Month', '3 Month'), ('6 Month', '6 Month'), ('1 Year', '3 Year'), ('More Than 1 Year', 'More Than 1 Year')], max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_details', to='accounts.profile')),
            ],
        ),
    ]
