# Generated by Django 3.2.5 on 2021-08-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0015_sponsorintroductiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royal_green_card', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('royal_yellow_card', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('royal_red_card', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('sms_alert', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('home_delevery', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('product_display', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('book_new_update', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('general_color_card', models.CharField(blank=True, max_length=10, null=True)),
                ('pvc_color_card', models.CharField(blank=True, max_length=10, null=True)),
                ('accouont_passbook', models.CharField(blank=True, max_length=10, null=True)),
                ('e_account_statement', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requireds', to='accounts.profile')),
            ],
        ),
    ]
