# Generated by Django 3.2.5 on 2021-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0017_auto_20210816_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequired',
            name='green_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='red_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='yellow_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
