# Generated by Django 3.2.5 on 2021-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0020_bussinesscardfees_account_passbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinesscardfees',
            name='e_account_statement',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bussinesscardfees',
            name='vc_general',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bussinesscardfees',
            name='vc_pvc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
