# Generated by Django 3.2.5 on 2021-08-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0021_auto_20210816_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequired',
            name='account_passbook_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
