# Generated by Django 3.2.5 on 2021-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0023_servicerequired_e_account_statement_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequired',
            name='general_color_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='pvc_color_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
