# Generated by Django 3.2.5 on 2021-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0024_auto_20210817_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequired',
            name='royal_blue_atm',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='royal_green_atm',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='royal_red_atm',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='royal_yellow_atm',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
