# Generated by Django 3.2.5 on 2021-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0025_auto_20210825_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequired',
            name='blue_atm_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='green_atm_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='red_atm_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequired',
            name='yellow_atm_card_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
