# Generated by Django 3.2.5 on 2021-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0026_auto_20210825_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinesscardfees',
            name='blue_atm_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bussinesscardfees',
            name='green_atm_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bussinesscardfees',
            name='red_atm_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bussinesscardfees',
            name='yellow_atm_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
