# Generated by Django 3.2.5 on 2021-08-26 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0027_auto_20210825_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('amount_in_figure', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_mode', models.CharField(blank=True, choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('ONLINE TRANSFER', 'ONLINE TRANSFER')], max_length=20, null=True)),
                ('upa_account_operation_mode', models.CharField(blank=True, choices=[('SELF', 'SELF'), ('JOINTLY', 'JOINTLY')], max_length=10, null=True)),
                ('joint_account', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_mode', to='accounts.profile')),
            ],
        ),
    ]
