# Generated by Django 3.2.5 on 2021-08-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('upa', '0028_operationmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_no', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_upa', models.CharField(blank=True, choices=[('WIFE', 'WIFE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('aadhar_card', models.CharField(blank=True, max_length=16, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=6, null=True)),
                ('extra_detail', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joint_account', to='accounts.profile')),
            ],
        ),
    ]
