# Generated by Django 3.2.5 on 2021-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0029_jointaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmode',
            name='aadhar_card_f',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='aadhar_card_s',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='account_no_f',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='account_no_s',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='address_one_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='address_one_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='address_two_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='address_two_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='dob_f',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='dob_s',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='email_f',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='email_s',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='extra_detail_f',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='extra_detail_s',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='gender_f',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='gender_s',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='marital_status_f',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='marital_status_s',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='mobile_no_f',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='mobile_no_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='name_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='name_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='relation_upa_f',
            field=models.CharField(blank=True, choices=[('WIFE', 'WIFE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='relation_upa_s',
            field=models.CharField(blank=True, choices=[('WIFE', 'WIFE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='uid_no_f',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operationmode',
            name='uid_no_s',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='JointAccount',
        ),
    ]
