# Generated by Django 3.2.5 on 2021-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0031_basicdetails_uid_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicdetails',
            name='uid_no',
        ),
    ]
