# Generated by Django 3.2.5 on 2021-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0032_remove_basicdetails_uid_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='upaaddress',
            name='same_as_above',
            field=models.BooleanField(default=False),
        ),
    ]
