# Generated by Django 3.2.5 on 2021-09-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0033_upaaddress_same_as_above'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='aadhar_card_add',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='aadhar_card_id',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='driving_add',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='driving_license_id',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='pan_card_id',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='passport_add',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='passport_id',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='ration_card_add',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='voter_card_add',
        ),
        migrations.RemoveField(
            model_name='upaidentityproof',
            name='voter_card_id',
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='address_proof',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('Voter ID Card', 'Voter ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='identity_proof',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('Voter ID Card', 'Voter ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=20, null=True),
        ),
    ]
