# Generated by Django 3.2.5 on 2021-09-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0034_auto_20210902_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='aadhar_card_add',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='aadhar_card_id',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='driving_license_add',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='driving_license_id',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='pan_card_id',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='passport_add',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='passport_id',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='ration_card_add',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='voter_card_add',
        ),
        migrations.RemoveField(
            model_name='beneficiarydetails',
            name='voter_card_id',
        ),
        migrations.AddField(
            model_name='beneficiarydetails',
            name='address_proof',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('Voter ID Card', 'Voter ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydetails',
            name='identity_proof',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('Voter ID Card', 'Voter ID Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=20, null=True),
        ),
    ]
