# Generated by Django 3.2.5 on 2021-09-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210831_1256'),
        ('upa', '0036_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_uid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_time', models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25')], max_length=2, null=True)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolment', to='accounts.profile')),
            ],
        ),
    ]
