# Generated by Django 3.2.5 on 2021-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0037_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
