# Generated by Django 3.2.5 on 2021-09-21 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profile_initial_form_status'),
        ('upa', '0038_alter_enrollment_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAddressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_three', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_four', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('active_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('std_code', models.PositiveIntegerField(blank=True, null=True)),
                ('isd_code', models.PositiveIntegerField(blank=True, null=True)),
                ('same_as_above', models.BooleanField(default=False)),
                ('p_address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_three', models.CharField(blank=True, max_length=100, null=True)),
                ('p_address_four', models.CharField(blank=True, max_length=100, null=True)),
                ('p_landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('p_town', models.CharField(blank=True, max_length=100, null=True)),
                ('p_dictrict', models.CharField(blank=True, max_length=100, null=True)),
                ('p_sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('p_postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('p_country', models.CharField(blank=True, max_length=100, null=True)),
                ('p_state', models.CharField(blank=True, max_length=100, null=True)),
                ('p_telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('p_mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('p_active_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('p_std_code', models.PositiveIntegerField(blank=True, null=True)),
                ('p_isd_code', models.PositiveIntegerField(blank=True, null=True)),
                ('upa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_address_details', to='accounts.profile')),
                ('user_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
