# Generated by Django 3.2.5 on 2021-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0039_changeaddressrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeaddressrecord',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
