# Generated by Django 3.2.5 on 2021-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0040_changeaddressrecord_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeaddressrecord',
            name='request_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeaddressrecord',
            name='upa_id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
