# Generated by Django 3.2.5 on 2022-10-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0042_changeadditionalrecord_changebeneficiaryrecord_changeoperationmoderecord_changeservicerequiredrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='gaurdian_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Father', 'Father'), ('Gaurdian', 'Gaurdian'), ('Spouse', 'Spouse')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='personal_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Smt', 'Smt')], default='Mr', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Smt', 'Smt')], default='Mr', max_length=3, null=True),
        ),
    ]
