# Generated by Django 3.2.5 on 2022-10-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0043_auto_20221023_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='gaurdian_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Father', 'Father'), ('Gaurdian', 'Gaurdian'), ('Spouse', 'Spouse')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydetails',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Smt', 'Smt')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='operationmode',
            name='joint_account',
            field=models.CharField(blank=True, choices=[('1', '1')], max_length=10, null=True),
        ),
    ]
