# Generated by Django 3.2.5 on 2022-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0044_auto_20221023_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='customer_education',
            field=models.CharField(blank=True, choices=[('Educated', 'Educated'), ('Illiterate/Un-educated', 'Illiterate/Un-educated')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='customer_nature',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Mature Female', 'Mature Female'), ('Senior Citizen', 'Senior Citizen')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='customer_work',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Un-employed', 'Un-employed')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='mother_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='Mrs', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='personal_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='Mr', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='Mr', max_length=3, null=True),
        ),
    ]
