# Generated by Django 3.2.5 on 2022-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0045_auto_20221029_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='customer_nature',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Mature Female', 'Mature Female'), ('Senior Citizen', 'Senior Citizen'), ('None Of The Above', 'None Of The Above')], max_length=40, null=True),
        ),
    ]
