# Generated by Django 3.2.5 on 2022-10-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0047_auto_20221029_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='upaidentityproof',
            name='bpl_ration_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='additinal_details/bpl/'),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='cmo_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='additinal_details/cmo/'),
        ),
    ]
