# Generated by Django 3.2.5 on 2022-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0048_auto_20221029_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='customer_education',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='customer_nature',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='customer_work',
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='customer_education',
            field=models.CharField(blank=True, choices=[('Educated', 'Educated'), ('Illiterate/Un-educated', 'Illiterate/Un-educated')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='customer_nature',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Mature Female', 'Mature Female'), ('Senior Citizen', 'Senior Citizen'), ('None Of The Above', 'None Of The Above')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='customer_work',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Un-employed', 'Un-employed')], max_length=15, null=True),
        ),
    ]
