# Generated by Django 3.2.5 on 2023-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0049_auto_20221030_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetails',
            name='religion',
            field=models.CharField(blank=True, choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
