# Generated by Django 3.2.5 on 2023-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0050_alter_additionaldetails_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydetails',
            name='beneficiary_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gaurdian_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Husband', 'Husband'), ('Gaurdian', 'Gaurdian'), ('Spouse', 'Spouse')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='upaidentityproof',
            name='upa_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=20, null=True),
        ),
    ]
