# Generated by Django 3.2.5 on 2023-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0052_auto_20230205_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='upaidentityproof',
            name='add_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='add_place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='add_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='address_proof/image/'),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='add_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='identity_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_proof/image/'),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upaidentityproof',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
