# Generated by Django 3.2.5 on 2023-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '0053_auto_20230205_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
